# Created by: Zhihao Yuan <lichray@gmail.com>
# $FreeBSD: head/chinese/libgooglepinyin/Makefile 357139 2014-06-09 11:21:52Z olgeni $

PORTNAME=	libgooglepinyin
PORTVERSION=	0.1.2
CATEGORIES=	chinese devel
MASTER_SITES=	${MASTER_SITE_GOOGLE_CODE}

MAINTAINER=	lichray@gmail.com
COMMENT=	Fork of Google Pinyin IME on Android

LICENSE=	APACHE20

USE_LDCONFIG=	yes
USES=		tar:bzip2 cmake

.include <bsd.port.mk>
