# $FreeBSD$

PORTNAME=	marisa-trie
PORTVERSION=	0.2.4
CATEGORIES=	devel textproc
DISTNAME=	marisa-${PORTVERSION}
MASTER_SITES=	GOOGLE_CODE

MAINTAINER=	lichray@gmail.com
COMMENT=	Matching Algorithm with Recursively Implemented StorAge

USES=		libtool pathfix pkgconfig
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
