# Created by: Zhihao Yuan <lichray@gmail.com>
# $FreeBSD: head/chinese/fcitx-table-extra/Makefile 339153 2014-01-08 16:12:38Z vanilla $

PORTNAME=	fcitx-table-extra
PORTVERSION=	0.3.5
CATEGORIES=	chinese
MASTER_SITES=	http://download.fcitx-im.org/${PORTNAME}/
DIST_SUBDIR=	fcitx

MAINTAINER=	lichray@gmail.com
COMMENT=	Table-based input methods for Fcitx

LICENSE=	GPLv2

LIB_DEPENDS=	libfcitx-config.so:${PORTSDIR}/chinese/fcitx

USES=		cmake gettext tar:xz
INSTALLS_ICONS=	yes
STRIP=

.include <bsd.port.mk>
