# Created by: Zhihao Yuan <lichray@gmail.com>
# $FreeBSD: head/chinese/opencc/Makefile 339854 2014-01-15 23:20:59Z bapt $

PORTNAME=	opencc
PORTVERSION=	1.0.2
CATEGORIES=	chinese converters

MAINTAINER=	lichray@gmail.com
COMMENT=	Open Chinese Convert library and utilities

LICENSE=	APACHE20

USES=		cmake
USE_LDCONFIG=	yes

USE_GITHUB=	yes
GH_ACCOUNT=	BYVoid
GH_PROJECT=	OpenCC
GH_TAGNAME=	ver.${DISTVERSION}
GH_COMMIT=	e684f54

.include <bsd.port.mk>
